package com.bfd.bdos.datafactory.task;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public class TExecuteReq {
	
	private String projectCode; // required
	private String taskCode; // required
	private String execName; // required
	private String command; // required
	private String params; // required
	private Integer typeCode; // required
	private String execUser; // required
	private Integer isMr; // required
	private String queue; // required
	private String execType; // required(tmp, ide, wf )
	private Integer queuePriority; // required

	private Long taskId;//资源id
	private String taskName;//资源名称
	
	private Boolean dataAccess;// 是否是数据接入

	public String getProjectCode() {
		return projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	public String getTaskCode() {
		return taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}

	public String getExecName() {
		return execName;
	}

	public void setExecName(String execName) {
		this.execName = execName;
	}

	public String getCommand() {
		return command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	public String getParams() {
		return params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	public Integer getTypeCode() {
		return typeCode;
	}

	public void setTypeCode(Integer typeCode) {
		this.typeCode = typeCode;
	}

	public String getExecUser() {
		return execUser;
	}

	public void setExecUser(String execUser) {
		this.execUser = execUser;
	}

	public Integer getIsMr() {
		return isMr;
	}

	public void setIsMr(Integer isMr) {
		this.isMr = isMr;
	}

	public String getQueue() {
		return queue;
	}

	public void setQueue(String queue) {
		this.queue = queue;
	}

	public String getExecType() {
		return execType;
	}

	public void setExecType(String execType) {
		this.execType = execType;
	}

	public Integer getQueuePriority() {
		return queuePriority;
	}

	public void setQueuePriority(Integer queuePriority) {
		this.queuePriority = queuePriority;
	}

	public Boolean getDataAccess() {
		return dataAccess;
	}

	public void setDataAccess(Boolean dataAccess) {
		this.dataAccess = dataAccess;
	}

	public Long getTaskId() {
		return taskId;
	}

	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	public String getTaskName() {
		return taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Override
	public String toString() {
		return "TExecuteReq [projectCode=" + projectCode + ", taskCode="
				+ taskCode + ", execName=" + execName + ", command=" + command
				+ ", params=" + params + ", typeCode=" + typeCode
				+ ", execUser=" + execUser + ", isMr=" + isMr + ", queue="
				+ queue + ", execType=" + execType + ", queuePriority="
				+ queuePriority + ", dataAccess=" + dataAccess + "]";
	}
	
}
